### ISSUE TITLE
Reusing video scaler causes segfault

### ISSUE THREAD

**Issue by panicbit** [panicbit/rust-av#17]
```
#0  0x00007ffff529b70b in ?? () from /usr/lib/libswscale.so.4
#1  0x00007ffff5247d0d in ?? () from /usr/lib/libswscale.so.4
#2  0x00007ffff527ccd8 in ?? () from /usr/lib/libswscale.so.4
#3  0x00007ffff527e1a4 in sws_scale () from /usr/lib/libswscale.so.4
#4  0x00005555555e7ae5 in av::scaler::Scaler::__scale (self=0x7fffe76ef298, source=0x7fffe321da00, source_stride=0x7fffe321da40, source_y=0, source_height=720, 
    target=0x7fffdbfe6000, target_stride=0x7fffdbfe6040) at <av>/src/scaler.rs:58
#5  0x00005555555e7c17 in av::scaler::Scaler::scale_frame (self=0x7fffe76ef298, source=0x7fffe32b1d88, target=0x7fffe76ef2d0) at <av>/src/scaler.rs:66
#6  0x0000555555573c8f in av::video::encoder::Encoder::encode<&mut av::video::frame::Frame> (self=0x7fffe76ef288, frame=0x7fffe32b1d88)
    at <av>/src/video/encoder.rs:76
#7  0x00005555555cb760 in stream::main () at <project>/examples/stream.rs:291
#8  0x00005555558068d6 in std::panicking::try::do_call<fn(),()> () at /checkout/src/libstd/panicking.rs:454
#9  0x000055555580db5b in panic_unwind::__rust_maybe_catch_panic () at /checkout/src/libpanic_unwind/lib.rs:98
#10 0x0000555555807387 in std::panicking::try<(),fn()> () at /checkout/src/libstd/panicking.rs:433
#11 std::panic::catch_unwind<fn(),()> () at /checkout/src/libstd/panic.rs:361
#12 std::rt::lang_start () at /checkout/src/libstd/rt.rs:57
#13 0x00005555555d22a3 in main ()
```

**Comment by panicbit** [comment]
Temporarily worked around in 2a15ea1 by creating a new scaler for each frame that needs scaling.

**Comment by panicbit** [comment]
A testcase for scaling should be added.
